parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Core\Shared\Infrastructure\Persistence\Doctrine\DoctrineRepositoryInterface:
            tags:
                - { name: core.persistence.doctrine.repository }

    App\:
        resource: '../app'

    Core\:
        resource: '../src/'
        exclude:
            - '../src/Shared/Infrastructur/Symfony/Kernel.php'
