parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Core\Shared\Domain\Bus\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        Core\Shared\Domain\Bus\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        Core\Shared\Domain\Bus\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

        Core\Shared\Infrastructure\Persistence\Doctrine\DoctrineRepositoryInterface:
            tags:
                - { name: core.persistence.doctrine.repository }

        Core\Shared\Infrastructure\Persistence\Doctrine\Types\AbstractType:
            tags:
                - { name: core.persistence.doctrine.type }

    App\:
        resource: '../app'
        tags:
            - { name: controller.service_arguments }

    Core\:
        resource: '../src/'
        exclude:
            - '../src/Shared/Infrastructure/Persistence/Doctrine/DoctrineAggregateRootManager.php'
            - '../src/Shared/Infrastructure/Symfony/Kernel.php'
