name: timetracker

services:
  api:
    image: timetracker-api
    container_name: timetracker.api
    environment:
      - APP_ENV=dev
    volumes:
      - ./backend:/app
    depends_on:
      - database

  app:
    image: timetracker-app
    container_name: timetracker.app
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app

  database:
    image: mariadb:latest
    container_name: timetracker.database
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql

  api-server:
    image: timetracker-server
    container_name: timetracker.server
    environment:
      - NGINX_APP_HOST=api
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
    depends_on:
      - api

volumes:
  db-data:
